#!/usr/bin/env python3
"""Configures local prerequisites for building HRX Demos Python wheels."""

from __future__ import annotations

import argparse
import os
import subprocess
import tempfile
from pathlib import Path
from typing import Optional

try:
    from .python_packaging import REPO_ROOT, discover_bazel, read_bazel_repo_env
except ImportError:
    from python_packaging import REPO_ROOT, discover_bazel, read_bazel_repo_env


BAZELISK_INSTRUCTIONS = """Install the pinned workspace-local Bazelisk from the workspace root:

  mkdir -p programs/bazel/bin programs/bazel/cache
  curl -fL https://github.com/bazelbuild/bazelisk/releases/download/v1.29.0/bazelisk-linux-amd64 \\
    -o programs/bazel/bin/bazel
  echo '5a408715e932c0250d28bd84555f12edbf70117de42f9181691c736eacc4a992  programs/bazel/bin/bazel' \\
    | sha256sum --check
  chmod +x programs/bazel/bin/bazel
  USE_BAZEL_VERSION=9.1.0 BAZELISK_HOME="$PWD/programs/bazel/cache" \\
    programs/bazel/bin/bazel --version

Then add that bin directory to PATH or pass --bazel explicitly.
"""


def _find_compiler(rocm_root: Path, names: tuple[str, ...]) -> Path:
    for directory in (
        rocm_root / "lib" / "llvm" / "bin",
        rocm_root / "llvm" / "bin",
        rocm_root / "bin",
    ):
        for name in names:
            candidate = directory / name
            if candidate.is_file() and os.access(candidate, os.X_OK):
                return candidate.resolve()
    raise RuntimeError(f"ROCm compiler {names[0]} was not found under {rocm_root}")


def validate_rocm_root(path: str) -> tuple[Path, Path, Path]:
    root = Path(path).expanduser().resolve()
    if not root.is_dir():
        raise RuntimeError(f"ROCm root does not exist: {root}")
    if not (root / "include").is_dir():
        raise RuntimeError(f"ROCm root has no include directory: {root}")
    if not (root / "lib" / "libhsa-runtime64.so.1").is_file():
        raise RuntimeError(f"ROCm root has no libhsa-runtime64.so.1: {root}")
    cc = _find_compiler(root, ("clang", "amdclang"))
    cxx = _find_compiler(root, ("clang++", "amdclang++"))
    return root, cc, cxx


def validate_bazel(bazel: Path) -> str:
    expected = (REPO_ROOT / ".bazelversion").read_text(encoding="utf-8").strip()
    result = subprocess.run(
        [str(bazel), "--version"],
        cwd=REPO_ROOT,
        check=True,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
    )
    output = result.stdout.strip()
    actual = output.rsplit(" ", 1)[-1]
    if actual != expected:
        raise RuntimeError(
            f"Bazel {expected} is required by .bazelversion; {bazel} reported {output!r}"
        )
    return output


def configured_values(rocm_root: Path, cc: Path, cxx: Path) -> dict[str, str]:
    return {
        "IREE_ROCM_PATH": str(rocm_root),
        "CC": str(cc),
        "CXX": str(cxx),
    }


def render_bazelrc(values: dict[str, str]) -> str:
    lines = [
        "# AUTO-GENERATED by build_tools/setup_python.py; do not edit.",
        "# Re-run the setup command to select a different ROCm installation.",
    ]
    for name in ("IREE_ROCM_PATH", "CC", "CXX"):
        lines.append(f"common --repo_env={name}={values[name]}")
    return "\n".join(lines) + "\n"


def _same_path(left: Optional[str], right: str) -> bool:
    if not left:
        return False
    return Path(left).expanduser().resolve() == Path(right).resolve()


def bazelrc_is_compatible(path: Path, expected: dict[str, str]) -> bool:
    existing = read_bazel_repo_env(path)
    return all(_same_path(existing.get(name), value) for name, value in expected.items())


def write_bazelrc(path: Path, contents: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary_name: Optional[str] = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            dir=path.parent,
            prefix=f".{path.name}.",
            delete=False,
        ) as temporary:
            temporary.write(contents)
            temporary_name = temporary.name
        os.replace(temporary_name, path)
    finally:
        if temporary_name and os.path.exists(temporary_name):
            os.unlink(temporary_name)


def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=__doc__,
        epilog=BAZELISK_INSTRUCTIONS,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--rocm",
        default=os.environ.get("IREE_ROCM_PATH") or os.environ.get("ROCM_PATH"),
        help="ROCm/TheRock installation root (defaults to IREE_ROCM_PATH or ROCM_PATH).",
    )
    parser.add_argument(
        "--bazel",
        help="Bazel or Bazelisk executable (defaults to BAZEL, PATH, or workspace programs/).",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Replace an incompatible existing .bazelrc.local.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_arguments()
    if not args.rocm:
        raise SystemExit("--rocm is required when no ROCm path is exported")
    if not (REPO_ROOT / "third_party" / "hrx-system" / "MODULE.bazel").is_file():
        raise SystemExit(
            "HRX submodule is not initialized; run `git submodule update --init`."
        )

    try:
        bazel = discover_bazel(args.bazel)
        bazel_version = validate_bazel(bazel)
        rocm_root, cc, cxx = validate_rocm_root(args.rocm)
    except (RuntimeError, subprocess.CalledProcessError) as error:
        if "Bazel" in str(error):
            raise SystemExit(f"{error}\n\n{BAZELISK_INSTRUCTIONS}") from error
        raise SystemExit(str(error)) from error

    rc_path = REPO_ROOT / ".bazelrc.local"
    values = configured_values(rocm_root, cc, cxx)
    if rc_path.exists() and bazelrc_is_compatible(rc_path, values):
        action = "Validated"
    elif rc_path.exists() and not args.force:
        raise SystemExit(
            f"{rc_path} has incompatible local settings; inspect it or rerun with --force."
        )
    else:
        write_bazelrc(rc_path, render_bazelrc(values))
        action = "Wrote"

    print(f"{action} {rc_path}")
    print(f"Bazel: {bazel} ({bazel_version})")
    print(f"ROCm: {rocm_root}")
    print("Python wheel prerequisites are configured.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
